library(readr)
library(bruceR)
library(emmeans)

# Load data
nd_data <- read_csv("C:/Users/ASUS/Desktop/nd_sim_21nov.csv")
sub1data = subset(nd_data, Group %in% c('HC', 'PS', 'NS'))
sub2data = subset(nd_data, Group %in% c('HC', 'PS', 'BA', 'WD'))

# 创建模型————三组
IC_model1 <- glm(IC ~ Group * (Prior_IC + Prior_WS + IC_pcs + WS_pcs + Pr_IC + Pr_WS), 
                 data = sub1data, family = gaussian())
WS_model1 <- glm(WS ~ Group * (Prior_IC + Prior_WS + IC_pcs + WS_pcs + Pr_IC + Pr_WS),
                 data = sub1data, family = gaussian())
model_summary(list(IC_model1, WS_model1))

# 分别提取每个交互项的边际均值和对比:IC
em_prior_ic <- emtrends(IC_model1, var = "Prior_IC", specs = ~ Group)
contrast_prior_ic <- contrast(em_prior_ic, method = list("PS vs NS" = c(0, -1, 1)))
em_prior_ws <- emtrends(IC_model1, var = "Prior_WS", specs = ~ Group)
contrast_prior_ws <- contrast(em_prior_ws, method = list("PS vs NS" = c(0, -1, 1)))
em_ic_pcs <- emtrends(IC_model1, var = "IC_pcs", specs = ~ Group)
contrast_ic_pcs <- contrast(em_ic_pcs, method = list("PS vs NS" = c(0, -1, 1)))
em_ws_pcs <- emtrends(IC_model1, var = "WS_pcs", specs = ~ Group)
contrast_ws_pcs <- contrast(em_ws_pcs, method = list("PS vs NS" = c(0, -1, 1)))
em_pr_ic <- emtrends(IC_model1, var = "Pr_IC", specs = ~ Group)
contrast_pr_ic <- contrast(em_pr_ic, method = list("PS vs NS" = c(0, -1, 1)))
em_pr_ws <- emtrends(IC_model1, var = "Pr_WS", specs = ~ Group)
contrast_pr_ws <- contrast(em_pr_ws, method = list("PS vs NS" = c(0, -1, 1)))

summary(contrast_prior_ic)
summary(contrast_prior_ws)
summary(contrast_ic_pcs)
summary(contrast_ws_pcs)
summary(contrast_pr_ic)
summary(contrast_pr_ws)

# 分别提取每个交互项的边际均值和对比:WS
em_prior_ic <- emtrends(WS_model1, var = "Prior_IC", specs = ~ Group)
contrast_prior_ic <- contrast(em_prior_ic, method = list("PS vs NS" = c(0, -1, 1)))
em_prior_ws <- emtrends(WS_model1, var = "Prior_WS", specs = ~ Group)
contrast_prior_ws <- contrast(em_prior_ws, method = list("PS vs NS" = c(0, -1, 1)))
em_ic_pcs <- emtrends(WS_model1, var = "IC_pcs", specs = ~ Group)
contrast_ic_pcs <- contrast(em_ic_pcs, method = list("PS vs NS" = c(0, -1, 1)))
em_ws_pcs <- emtrends(WS_model1, var = "WS_pcs", specs = ~ Group)
contrast_ws_pcs <- contrast(em_ws_pcs, method = list("PS vs NS" = c(0, -1, 1)))
em_pr_ic <- emtrends(WS_model1, var = "Pr_IC", specs = ~ Group)
contrast_pr_ic <- contrast(em_pr_ic, method = list("PS vs NS" = c(0, -1, 1)))
em_pr_ws <- emtrends(WS_model1, var = "Pr_WS", specs = ~ Group)
contrast_pr_ws <- contrast(em_pr_ws, method = list("PS vs NS" = c(0, -1, 1)))

summary(contrast_prior_ic)
summary(contrast_prior_ws)
summary(contrast_ic_pcs)
summary(contrast_ws_pcs)
summary(contrast_pr_ic)
summary(contrast_pr_ws)

# 创建模型————四组
IC_model2 <- glm(IC ~ Group * (Prior_IC + Prior_WS + IC_pcs + WS_pcs + Pr_IC + Pr_WS), 
                 data = sub2data, family = gaussian())
WS_model2 <- glm(WS ~ Group * (Prior_IC + Prior_WS + IC_pcs + WS_pcs + Pr_IC + Pr_WS),
                 data = sub2data, family = gaussian())
model_summary(list(IC_model2, WS_model2))

# 分别提取每个交互项的边际均值和对比:IC
em_prior_ic <- emtrends(IC_model2, var = "Prior_IC", specs = ~ Group)
contrast_prior_ic1 <- contrast(em_prior_ic, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_prior_ic2 <- contrast(em_prior_ic, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_prior_ic3 <- contrast(em_prior_ic, method = list("BA vs WD" = c(0, 0, -1, 1)))
em_prior_ws <- emtrends(IC_model2, var = "Prior_WS", specs = ~ Group)
contrast_prior_ws1 <- contrast(em_prior_ws, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_prior_ws2 <- contrast(em_prior_ws, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_prior_ws3 <- contrast(em_prior_ws, method = list("BA vs WD" = c(0, 0, -1, 1)))
em_ic_pcs <- emtrends(IC_model2, var = "IC_pcs", specs = ~ Group)
contrast_ic_pcs1 <- contrast(em_ic_pcs, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_ic_pcs2 <- contrast(em_ic_pcs, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_ic_pcs3 <- contrast(em_ic_pcs, method = list("BA vs WD" = c(0, 0, -1, 1)))
em_ws_pcs <- emtrends(IC_model2, var = "WS_pcs", specs = ~ Group)
contrast_ws_pcs1 <- contrast(em_ws_pcs, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_ws_pcs2 <- contrast(em_ws_pcs, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_ws_pcs3 <- contrast(em_ws_pcs, method = list("BA vs WD" = c(0, 0, -1, 1)))
em_pr_ic <- emtrends(IC_model2, var = "Pr_IC", specs = ~ Group)
contrast_pr_ic1 <- contrast(em_pr_ic, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_pr_ic2 <- contrast(em_pr_ic, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_pr_ic3 <- contrast(em_pr_ic, method = list("BA vs WD" = c(0, 0, -1, 1)))
em_pr_ws <- emtrends(IC_model2, var = "Pr_WS", specs = ~ Group)
contrast_pr_ws1 <- contrast(em_pr_ws, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_pr_ws2 <- contrast(em_pr_ws, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_pr_ws3 <- contrast(em_pr_ws, method = list("BA vs WD" = c(0, 0, -1, 1)))

summary(contrast_prior_ic1)
summary(contrast_prior_ic2)
summary(contrast_prior_ic3)
summary(contrast_prior_ws1)
summary(contrast_prior_ws2)
summary(contrast_prior_ws3)
summary(contrast_ic_pcs1)
summary(contrast_ic_pcs2)
summary(contrast_ic_pcs3)
summary(contrast_ws_pcs1)
summary(contrast_ws_pcs2)
summary(contrast_ws_pcs3)
summary(contrast_pr_ic1)
summary(contrast_pr_ic2)
summary(contrast_pr_ic3)
summary(contrast_pr_ws1)
summary(contrast_pr_ws2)
summary(contrast_pr_ws3)

# 分别提取每个交互项的边际均值和对比:WS
em_prior_ic <- emtrends(WS_model2, var = "Prior_IC", specs = ~ Group)
contrast_prior_ic1 <- contrast(em_prior_ic, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_prior_ic2 <- contrast(em_prior_ic, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_prior_ic3 <- contrast(em_prior_ic, method = list("BA vs WD" = c(0, 0, -1, 1)))
em_prior_ws <- emtrends(WS_model2, var = "Prior_WS", specs = ~ Group)
contrast_prior_ws1 <- contrast(em_prior_ws, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_prior_ws2 <- contrast(em_prior_ws, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_prior_ws3 <- contrast(em_prior_ws, method = list("BA vs WD" = c(0, 0, -1, 1)))
em_ic_pcs <- emtrends(WS_model2, var = "IC_pcs", specs = ~ Group)
contrast_ic_pcs1 <- contrast(em_ic_pcs, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_ic_pcs2 <- contrast(em_ic_pcs, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_ic_pcs3 <- contrast(em_ic_pcs, method = list("BA vs WD" = c(0, 0, -1, 1)))
em_ws_pcs <- emtrends(WS_model2, var = "WS_pcs", specs = ~ Group)
contrast_ws_pcs1 <- contrast(em_ws_pcs, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_ws_pcs2 <- contrast(em_ws_pcs, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_ws_pcs3 <- contrast(em_ws_pcs, method = list("BA vs WD" = c(0, 0, -1, 1)))
em_pr_ic <- emtrends(WS_model2, var = "Pr_IC", specs = ~ Group)
contrast_pr_ic1 <- contrast(em_pr_ic, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_pr_ic2 <- contrast(em_pr_ic, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_pr_ic3 <- contrast(em_pr_ic, method = list("BA vs WD" = c(0, 0, -1, 1)))
em_pr_ws <- emtrends(WS_model2, var = "Pr_WS", specs = ~ Group)
contrast_pr_ws1 <- contrast(em_pr_ws, method = list("PS vs BA" = c(0, -1, 1, 0)))
contrast_pr_ws2 <- contrast(em_pr_ws, method = list("PS vs WD" = c(0, -1, 0, 1)))
contrast_pr_ws3 <- contrast(em_pr_ws, method = list("BA vs WD" = c(0, 0, -1, 1)))

summary(contrast_prior_ic1)
summary(contrast_prior_ic2)
summary(contrast_prior_ic3)
summary(contrast_prior_ws1)
summary(contrast_prior_ws2)
summary(contrast_prior_ws3)
summary(contrast_ic_pcs1)
summary(contrast_ic_pcs2)
summary(contrast_ic_pcs3)
summary(contrast_ws_pcs1)
summary(contrast_ws_pcs2)
summary(contrast_ws_pcs3)
summary(contrast_pr_ic1)
summary(contrast_pr_ic2)
summary(contrast_pr_ic3)
summary(contrast_pr_ws1)
summary(contrast_pr_ws2)
summary(contrast_pr_ws3)